/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AdminModeration: () => import('#controllers/admin_moderation_controller'),
  AuthRegisters: () => import('#controllers/auth_registers_controller'),
  AuthSessions: () => import('#controllers/auth_sessions_controller'),
  ChatMessages: () => import('#controllers/chat_messages_controller'),
  DriverDashboard: () => import('#controllers/driver_dashboard_controller'),
  DriverRouteTemplates: () => import('#controllers/driver_route_templates_controller'),
  DriverTripPassengers: () => import('#controllers/driver_trip_passengers_controller'),
  DriverTripRequests: () => import('#controllers/driver_trip_requests_controller'),
  Onboarding: () => import('#controllers/onboarding_controller'),
  PassengerHome: () => import('#controllers/passenger_home_controller'),
  PassengerMyTrips: () => import('#controllers/passenger_my_trips_controller'),
  PassengerRouteSuggestions: () => import('#controllers/passenger_route_suggestions_controller'),
  PassengerTrips: () => import('#controllers/passenger_trips_controller'),
  Profile: () => import('#controllers/profile_controller'),
  TripRequests: () => import('#controllers/trip_requests_controller'),
}
