/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class DriverProfileSchema extends BaseModel {
  static $columns = ['approvalStatus', 'commuteNotes', 'createdAt', 'detourToleranceMinutes', 'id', 'pickupRadiusMeters', 'plateNumber', 'seatsTotal', 'updatedAt', 'userId', 'vehicleColor', 'vehicleMake', 'vehicleModel'] as const
  $columns = DriverProfileSchema.$columns
  @column()
  declare approvalStatus: string
  @column()
  declare commuteNotes: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare detourToleranceMinutes: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare pickupRadiusMeters: number | null
  @column()
  declare plateNumber: string | null
  @column()
  declare seatsTotal: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare vehicleColor: string | null
  @column()
  declare vehicleMake: string | null
  @column()
  declare vehicleModel: string | null
}

export class ModerationActionSchema extends BaseModel {
  static $columns = ['actionType', 'adminUserId', 'createdAt', 'id', 'metadataJson', 'reason', 'targetUserId', 'updatedAt'] as const
  $columns = ModerationActionSchema.$columns
  @column()
  declare actionType: string
  @column()
  declare adminUserId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metadataJson: any | null
  @column()
  declare reason: string | null
  @column()
  declare targetUserId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ModerationReportSchema extends BaseModel {
  static $columns = ['createdAt', 'details', 'id', 'reason', 'reportedByUserId', 'reportedUserId', 'status', 'tripInstanceId', 'updatedAt'] as const
  $columns = ModerationReportSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare details: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare reason: string
  @column()
  declare reportedByUserId: number
  @column()
  declare reportedUserId: number
  @column()
  declare status: string
  @column()
  declare tripInstanceId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PassengerProfileSchema extends BaseModel {
  static $columns = ['accessibilityNotes', 'createdAt', 'id', 'preferredEveningTime', 'preferredMorningTime', 'ridePreferences', 'updatedAt', 'userId', 'usualCommuteDays'] as const
  $columns = PassengerProfileSchema.$columns
  @column()
  declare accessibilityNotes: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare preferredEveningTime: string | null
  @column()
  declare preferredMorningTime: string | null
  @column()
  declare ridePreferences: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare usualCommuteDays: string | null
}

export class PassengerRouteCorridorInterestSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'message', 'riderUserId', 'routeTemplateId', 'updatedAt'] as const
  $columns = PassengerRouteCorridorInterestSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string | null
  @column()
  declare riderUserId: number
  @column()
  declare routeTemplateId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PublicProfileSchema extends BaseModel {
  static $columns = ['alias', 'avatar', 'completedTrips', 'createdAt', 'id', 'onTimeScore', 'rating', 'updatedAt', 'userId'] as const
  $columns = PublicProfileSchema.$columns
  @column()
  declare alias: string
  @column()
  declare avatar: string
  @column()
  declare completedTrips: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare onTimeScore: string | null
  @column()
  declare rating: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class RouteTemplateScheduleSchema extends BaseModel {
  static $columns = ['createdAt', 'dayOfWeek', 'id', 'isActive', 'routeTemplateId', 'updatedAt'] as const
  $columns = RouteTemplateScheduleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dayOfWeek: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare routeTemplateId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RouteTemplateSchema extends BaseModel {
  static $columns = ['createdAt', 'departureTime', 'destinationLabel', 'destinationLat', 'destinationLng', 'destinationPlaceId', 'detourToleranceMinutes', 'driverUserId', 'id', 'originLabel', 'originLat', 'originLng', 'originPlaceId', 'pickupRadiusMeters', 'routePolyline', 'scheduleType', 'seatsTotal', 'status', 'totalDistanceMeters', 'totalDurationSeconds', 'updatedAt'] as const
  $columns = RouteTemplateSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare departureTime: string
  @column()
  declare destinationLabel: string
  @column()
  declare destinationLat: string
  @column()
  declare destinationLng: string
  @column()
  declare destinationPlaceId: string | null
  @column()
  declare detourToleranceMinutes: number
  @column()
  declare driverUserId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare originLabel: string
  @column()
  declare originLat: string
  @column()
  declare originLng: string
  @column()
  declare originPlaceId: string | null
  @column()
  declare pickupRadiusMeters: number | null
  @column()
  declare routePolyline: string | null
  @column()
  declare scheduleType: string
  @column()
  declare seatsTotal: number
  @column()
  declare status: string
  @column()
  declare totalDistanceMeters: number | null
  @column()
  declare totalDurationSeconds: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SavedPlaceSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isDefault', 'kind', 'label', 'lat', 'lng', 'placeId', 'updatedAt', 'userId'] as const
  $columns = SavedPlaceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDefault: boolean
  @column()
  declare kind: string
  @column()
  declare label: string
  @column()
  declare lat: string
  @column()
  declare lng: string
  @column()
  declare placeId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class TripInstanceSchema extends BaseModel {
  static $columns = ['createdAt', 'departureTime', 'driverUserId', 'exactPickupUnlocked', 'id', 'routePolyline', 'routeStatus', 'routeTemplateId', 'seatsRemaining', 'seatsTotal', 'totalDistanceMeters', 'totalDurationSeconds', 'tripDate', 'updatedAt'] as const
  $columns = TripInstanceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare departureTime: string
  @column()
  declare driverUserId: number
  @column()
  declare exactPickupUnlocked: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare routePolyline: string | null
  @column()
  declare routeStatus: string
  @column()
  declare routeTemplateId: number | null
  @column()
  declare seatsRemaining: number
  @column()
  declare seatsTotal: number
  @column()
  declare totalDistanceMeters: number | null
  @column()
  declare totalDurationSeconds: number | null
  @column.date()
  declare tripDate: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TripMessageSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'message', 'recipientUserId', 'senderUserId', 'tripInstanceId', 'updatedAt'] as const
  $columns = TripMessageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string
  @column()
  declare recipientUserId: number | null
  @column()
  declare senderUserId: number
  @column()
  declare tripInstanceId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TripPassengerSchema extends BaseModel {
  static $columns = ['confirmedPickupLabel', 'confirmedPickupLat', 'confirmedPickupLng', 'createdAt', 'id', 'riderUserId', 'seatCount', 'status', 'tripInstanceId', 'tripRequestId', 'updatedAt'] as const
  $columns = TripPassengerSchema.$columns
  @column()
  declare confirmedPickupLabel: string | null
  @column()
  declare confirmedPickupLat: string | null
  @column()
  declare confirmedPickupLng: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare riderUserId: number
  @column()
  declare seatCount: number
  @column()
  declare status: string
  @column()
  declare tripInstanceId: number
  @column()
  declare tripRequestId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TripRequestSchema extends BaseModel {
  static $columns = ['approxPickupLabel', 'approxPickupLat', 'approxPickupLng', 'approxPickupRadiusMeters', 'createdAt', 'exactPickupLabel', 'exactPickupLat', 'exactPickupLng', 'id', 'message', 'respondedAt', 'riderUserId', 'status', 'tripInstanceId', 'updatedAt'] as const
  $columns = TripRequestSchema.$columns
  @column()
  declare approxPickupLabel: string
  @column()
  declare approxPickupLat: string
  @column()
  declare approxPickupLng: string
  @column()
  declare approxPickupRadiusMeters: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare exactPickupLabel: string | null
  @column()
  declare exactPickupLat: string | null
  @column()
  declare exactPickupLng: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string | null
  @column.dateTime()
  declare respondedAt: DateTime | null
  @column()
  declare riderUserId: number
  @column()
  declare status: string
  @column()
  declare tripInstanceId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['canDrive', 'canRide', 'createdAt', 'departmentTeam', 'email', 'emergencyContactName', 'emergencyContactPhone', 'id', 'isAdmin', 'onboardingCompletedAt', 'password', 'phone', 'realName', 'status', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare canDrive: boolean
  @column()
  declare canRide: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare departmentTeam: string | null
  @column()
  declare email: string
  @column()
  declare emergencyContactName: string | null
  @column()
  declare emergencyContactPhone: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isAdmin: boolean
  @column.dateTime()
  declare onboardingCompletedAt: DateTime | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare phone: string | null
  @column()
  declare realName: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
